### ISSUE TITLE
Please add single file option

### ISSUE THREAD

**Issue by hm-tamim** [Chaos-woo/json-dart-serializable#1]
Please add an option to generate the classes in a single dart file

**Comment by Chaos-woo** [comment]
I want to depends on Dart other plugins [json_serializable](https://pub.dev/packages/json_serializable) 
and [json_annotation](https://pub.dev/packages/json_annotation) to generate `toJson` and `fromJson` methods. But, i don't know if they currently support.

I remember before that I wanted to put all the internal objects in Json into a Dart file to reduce the generated Json dart files and it's *.g.dart files. I thought I could study how to handle it again.  I hope that your suggestion may be supported in version 0.9. In a project code that I am currently working, I divide it into multiple folders based on Json content to better locate them.

e.g.
```
models(package)
  - chat-completions(package)
    - chat_completion.dart
    - chat.dart
    - message.dart
  - chat-models(package)
    - chat_model.dart
```

Hope it can help you

**Comment by Chaos-woo** [comment]
Just now I tried writing two classes in a dart file. Then, use `flutter packages pub run build_runner build --delete-conflicting-outputs` command can generate two `toJson` and `fromJson` methods in a *. g.dart file. I will add this feature in version 0.9. Thanks your suggestion. @hm-tamim 

The code for the experiment is as follows:

```dart
import 'package:json_annotation/json_annotation.dart';

part 'example.g.dart';

/// messages
@JsonSerializable()
class Example {
  String content;

  /// Constructor...
  Example({
    required this.content,
  });

  /// Deserializer...
  factory Example.fromJson(Map<String, dynamic> json) => _$ExampleFromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$ExampleToJson(this);
}

@JsonSerializable()
class Example0 {
  String content1;

  /// Constructor...
  Example0({
    required this.content1,
  });

  /// Deserializer...
  factory Example0.fromJson(Map<String, dynamic> json) => _$Example0FromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$Example0ToJson(this);
}
```

generated example.g.dart file
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'example.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Example _$ExampleFromJson(Map<String, dynamic> json) => Example(
      content: json['content'] as String,
    );

Map<String, dynamic> _$ExampleToJson(Example instance) => <String, dynamic>{
      'content': instance.content,
    };

Example0 _$Example0FromJson(Map<String, dynamic> json) => Example0(
      content1: json['content1'] as String,
    );

Map<String, dynamic> _$Example0ToJson(Example0 instance) => <String, dynamic>{
      'content1': instance.content1,
    };
```

**Comment by Chaos-woo** [comment]
I suddenly remembered before that I wanted to generate all *.g.dart files in a named `Generated` folder, and I found that this is similar to [json_serializable](https://pub.dev/packages/json_serializable) plugin is no longer relevant, which is different from your suggestion. I remember it incorrectly, HaHa   .   @hm-tamim

**Comment by Chaos-woo** [comment]
I has added [All Json objects generated dart classes into single file] function in v0.9. Currently, I has uploaded new version plugin to Jetbrains plugins marketplace, later you will download it. 

If @hm-tamim  has other suggestions, please post issues again.   More see [json-dart-serializable](https://plugins.jetbrains.com/plugin/21392-json-dart-serializable)
